# Generated by Django 4.1.1 on 2022-12-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillinmultipleblanksoption',
            name='answer',
        ),
        migrations.DeleteModel(
            name='FillInMultipleBlanks',
        ),
        migrations.DeleteModel(
            name='FillInMultipleBlanksOption',
        ),
    ]
