# Generated by Django 4.1.1 on 2023-02-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='fill_in_single_blank',
            field=models.TextField(blank=True, null=True),
        ),
    ]
