# Generated by Django 4.1.1 on 2023-02-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0008_remove_useranswer_answer'),
        ('answers', '0002_alter_answer_fill_in_single_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='algorithm.useranswer'),
            preserve_default=False,
        ),
    ]
