# Generated by Django 4.1.1 on 2023-03-21 09:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_semestercode_unique_id_semester'),
        ('answers', '0003_answer_user_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('timeout_seconds', models.IntegerField(default=1)),
                ('memory_limit', models.CharField(default='128m', max_length=10)),
                ('tests', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.problem')),
            ],
        ),
        migrations.CreateModel(
            name='CodeAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_code', models.TextField()),
                ('tests_result', models.TextField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.code')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='code_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='answers.codeanswer'),
        ),
    ]
