# Generated by Django 4.1.1 on 2023-02-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='skill_level',
            field=models.FloatField(default=1.4),
        ),
    ]
