# Generated by Django 4.1.1 on 2023-02-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_progress_skill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weakestlinkproblem',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='weakestlinkproblem',
            name='progress',
        ),
        migrations.DeleteModel(
            name='UserCurrentProgress',
        ),
        migrations.DeleteModel(
            name='WeakestLinkProblem',
        ),
    ]
