# Generated by Django 4.1.1 on 2023-02-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0003_remove_weakestlinkproblem_problem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theoryprogress',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='theory',
        ),
        migrations.AddField(
            model_name='progress',
            name='practice_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='progress',
            name='theory_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='PracticeProgress',
        ),
        migrations.DeleteModel(
            name='TheoryProgress',
        ),
    ]
