# Generated by Django 4.1.1 on 2023-02-19 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_algorithm_correct_answer_bonus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('algorithm', '0004_remove_theoryprogress_topic_remove_progress_practice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='weakest_link_state',
        ),
        migrations.RemoveField(
            model_name='weakestlinktopic',
            name='progress',
        ),
        migrations.AddField(
            model_name='weakestlinktopic',
            name='group_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weakestlinktopic',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weakestlinktopic',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WeakestLinkProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_number', models.IntegerField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.problem')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserWeakestLinkState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('None', 'Weakest Link not started'), ('In progress', 'Weakest Link in progress'), ('Done', 'Weakest Link done')], default='None', max_length=11)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userweakestlinkstate',
            constraint=models.UniqueConstraint(fields=('user', 'semester'), name='unique_user_semester'),
        ),
    ]
