# Generated by Django 4.1.1 on 2023-02-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0006_topicgraphedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='weakestlinkproblem',
            name='is_solved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
