# Generated by Django 4.1.1 on 2023-02-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0007_weakestlinkproblem_is_solved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='answer',
        ),
    ]
