# Generated by Django 4.1.1 on 2023-03-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0008_remove_useranswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='coefficient',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='progress',
            name='skill_level',
            field=models.FloatField(default=1.7),
        ),
    ]
