# Generated by Django 4.1.1 on 2023-04-26 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('algorithm', '0009_useranswer_coefficient_alter_progress_skill_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTargetPoints',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('target_points', models.IntegerField(choices=[(61, '61'), (76, '76'), (91, '91')], default=91)),
            ],
        ),
    ]
