# Generated by Django 4.1.1 on 2023-05-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0010_useranswer_time_elapsed_in_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='is_solved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
