# Generated by Django 4.1.1 on 2023-04-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0010_usertargetpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertargetpoints',
            name='target_points',
            field=models.IntegerField(choices=[(61, '3'), (76, '4'), (91, '5')], default=91),
        ),
    ]
