# Generated by Django 4.1.1 on 2023-02-08 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnails/')),
                ('topic_threshold_low', models.IntegerField(default=61)),
                ('topic_threshold_medium', models.IntegerField(default=76)),
                ('topic_threshold_high', models.IntegerField(default=91)),
                ('topic_theory_max_points', models.IntegerField(default=40)),
                ('topic_practice_max_points', models.IntegerField(default=60)),
                ('points_easy', models.IntegerField(default=2)),
                ('points_normal', models.IntegerField(default=5)),
                ('points_hard', models.IntegerField(default=9)),
                ('difficulty_threshold_normal', models.IntegerField(default=3)),
                ('difficulty_threshold_hard', models.IntegerField(default=2)),
                ('sub_topic_points_coefficient', models.FloatField(default=0.3333333333333333)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('is_required', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('time_to_complete', models.IntegerField()),
                ('is_required', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('students', models.ManyToManyField(related_name='semester_student_set', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(related_name='semester_teacher_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Multiple Choice Radio', 'Выбор одного варианта'), ('Multiple Choice Checkbox', 'Выбор нескольких вариантов'), ('Fill In Single Blank', 'Заполнение пропуска')], max_length=100)),
                ('difficulty', models.IntegerField(choices=[(1, 'Легкое'), (2, 'Нормальное'), (3, 'Сложное')])),
                ('main_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_main_set', to='courses.topic')),
                ('sub_topics', models.ManyToManyField(blank=True, related_name='problem_sub_set', to='courses.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.topic')),
            ],
        ),
    ]
