# Generated by Django 4.1.1 on 2023-02-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.CharField(choices=[('Multiple Choice Radio', 'Выбор одного варианта'), ('Multiple Choice Checkbox', 'Выбор нескольких вариантов'), ('Fill In Single Blank', 'Заполнение пропуска'), ('Code', 'Код')], max_length=100),
        ),
    ]
