# Generated by Django 4.1.1 on 2022-11-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.CharField(choices=[('Multiple Choice Radio', 'Multiple Choice Radio'), ('Multiple Choice Checkbox', 'Multiple Choice Checkbox'), ('Fill In Single Blank', 'Fill In Single Blank'), ('Fill In Multiple Blanks', 'Fill In Multiple Blanks')], max_length=100),
        ),
    ]
