# Generated by Django 4.1.1 on 2023-02-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='algorithm_correct_answer_bonus',
            field=models.FloatField(default=0.05, editable=False),
        ),
        migrations.AddField(
            model_name='course',
            name='algorithm_difficulty_coefficient_easy',
            field=models.FloatField(default=0.3, editable=False),
        ),
        migrations.AddField(
            model_name='course',
            name='algorithm_difficulty_coefficient_hard',
            field=models.FloatField(default=0.9, editable=False),
        ),
        migrations.AddField(
            model_name='course',
            name='algorithm_difficulty_coefficient_normal',
            field=models.FloatField(default=0.6, editable=False),
        ),
        migrations.AddField(
            model_name='course',
            name='algorithm_suitable_difficulty_probability',
            field=models.FloatField(default=0.75, editable=False),
        ),
        migrations.AddField(
            model_name='course',
            name='algorithm_wrong_answer_penalty',
            field=models.FloatField(default=0.07, editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty_threshold_hard',
            field=models.IntegerField(default=2, editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty_threshold_normal',
            field=models.IntegerField(default=3, editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='sub_topic_points_coefficient',
            field=models.FloatField(default=0.3333333333333333, editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='topic_practice_max_points',
            field=models.IntegerField(default=60, editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='topic_theory_max_points',
            field=models.IntegerField(default=40, editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='topic_threshold_high',
            field=models.IntegerField(default=91, editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='topic_threshold_low',
            field=models.IntegerField(default=61, editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='topic_threshold_medium',
            field=models.IntegerField(default=76, editable=False),
        ),
    ]
