# Generated by Django 4.1.1 on 2022-12-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='value',
        ),
    ]
