# Generated by Django 4.1.1 on 2023-02-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_algorithm_correct_answer_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='algorithm_skill_level_placement_answers',
            field=models.FloatField(default=5, editable=False),
        ),
    ]
