# Generated by Django 4.1.1 on 2022-12-21 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_remove_problem_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='students',
            field=models.ManyToManyField(related_name='semester_student_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semester',
            name='teachers',
            field=models.ManyToManyField(related_name='semester_teacher_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
