# Generated by Django 4.1.1 on 2023-02-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_algorithm_skill_level_placement_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='algorithm_correct_answer_bonus',
        ),
        migrations.RemoveField(
            model_name='course',
            name='algorithm_difficulty_coefficient_easy',
        ),
        migrations.RemoveField(
            model_name='course',
            name='algorithm_difficulty_coefficient_hard',
        ),
        migrations.RemoveField(
            model_name='course',
            name='algorithm_difficulty_coefficient_normal',
        ),
        migrations.RemoveField(
            model_name='course',
            name='algorithm_skill_level_placement_answers',
        ),
        migrations.RemoveField(
            model_name='course',
            name='algorithm_suitable_difficulty_probability',
        ),
        migrations.RemoveField(
            model_name='course',
            name='algorithm_wrong_answer_penalty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='difficulty_threshold_hard',
        ),
        migrations.RemoveField(
            model_name='course',
            name='difficulty_threshold_normal',
        ),
        migrations.RemoveField(
            model_name='course',
            name='points_easy',
        ),
        migrations.RemoveField(
            model_name='course',
            name='points_hard',
        ),
        migrations.RemoveField(
            model_name='course',
            name='points_normal',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sub_topic_points_coefficient',
        ),
        migrations.RemoveField(
            model_name='course',
            name='topic_practice_max_points',
        ),
        migrations.RemoveField(
            model_name='course',
            name='topic_theory_max_points',
        ),
        migrations.RemoveField(
            model_name='course',
            name='topic_threshold_high',
        ),
        migrations.RemoveField(
            model_name='course',
            name='topic_threshold_low',
        ),
        migrations.RemoveField(
            model_name='course',
            name='topic_threshold_medium',
        ),
    ]
