# Generated by Django 4.1.1 on 2023-03-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_semestercode'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='semestercode',
            constraint=models.UniqueConstraint(fields=('id', 'semester'), name='unique_id_semester'),
        ),
    ]
